// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAX0ozPqhCtVa5DjoLdqgPhRuAHr3oY0sQ',
    appId: '1:1013540512760:web:d8d2116d326d03b47a2c0d',
    messagingSenderId: '1013540512760',
    projectId: 'medicare-a134f',
    authDomain: 'medicare-a134f.firebaseapp.com',
    storageBucket: 'medicare-a134f.firebasestorage.app',
    measurementId: 'G-SSFNWHNCEQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2NJZu0CLAGUZBG8Avx5RDByfYt_lrdkE',
    appId: '1:1013540512760:android:4147865d5dca36f87a2c0d',
    messagingSenderId: '1013540512760',
    projectId: 'medicare-a134f',
    storageBucket: 'medicare-a134f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTlJKnfCJw5MOHqlGniGb_6n7_CdiGEfY',
    appId: '1:1013540512760:ios:0436678358acb2447a2c0d',
    messagingSenderId: '1013540512760',
    projectId: 'medicare-a134f',
    storageBucket: 'medicare-a134f.firebasestorage.app',
    iosBundleId: 'com.example.crudApi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTlJKnfCJw5MOHqlGniGb_6n7_CdiGEfY',
    appId: '1:1013540512760:ios:0436678358acb2447a2c0d',
    messagingSenderId: '1013540512760',
    projectId: 'medicare-a134f',
    storageBucket: 'medicare-a134f.firebasestorage.app',
    iosBundleId: 'com.example.crudApi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAX0ozPqhCtVa5DjoLdqgPhRuAHr3oY0sQ',
    appId: '1:1013540512760:web:0a47895ddf5316b27a2c0d',
    messagingSenderId: '1013540512760',
    projectId: 'medicare-a134f',
    authDomain: 'medicare-a134f.firebaseapp.com',
    storageBucket: 'medicare-a134f.firebasestorage.app',
    measurementId: 'G-RXE7V4Q2TP',
  );
}
